[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/golang/snappy"
  version = "0.0.1"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.8.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = '1.5.1'

[[constraint]]
  name = "github.com/wavefronthq/wavefront-sdk-go"
  version = "0.9.5"

[[override]]
  name = "github.com/caio/go-tdigest"
  version = "2.3.0"

[prune]
  go-tests = true
  unused-packages = true
